// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxkbialxdotzikbvjzfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4a2JpYWx4ZG90emlrYnZqemZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTM0MjIsImV4cCI6MjA2NTQ4OTQyMn0.zLzwaDMx3vjQ46yOx54_RWRRDlRfFwezR73LR50jLQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);